//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public string SrudentName { get; set; }
        public string Address { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public string Email { get; set; }
        public Nullable<int> SSN { get; set; }
        public string Teacher { get; set; }
    
        public virtual Departments Departments { get; set; }
    }
}
